import { NextResponse } from "next/server";
import { kv } from "@vercel/kv";

export interface PrevPlayerStat {
  name: string;
  jersey: number;
  team: string;
  divisionLabel: string;
  divisionRank: number;
  gp: number;
  goals: number;
  assists: number;
  points: number;
  pim: number;
}

const KV_KEY = "season:52:players";

// 52ndシーズン個人成績（Wayback Machine より取得・ハードコード）
const SEASON_52_PLAYERS: PrevPlayerStat[] = [
// Total: 431 players
  { name: "高山智宏", jersey: 4, team: "Flying Penguins", divisionLabel: "Platinum", divisionRank: 1, gp: 4, goals: 9, assists: 12, points: 21, pim: 0 },
  { name: "叶多洸大", jersey: 12, team: "かんだ食堂", divisionLabel: "Platinum", divisionRank: 2, gp: 3, goals: 11, assists: 5, points: 16, pim: 0 },
  { name: "石渡逸成", jersey: 14, team: "かんだ食堂", divisionLabel: "Platinum", divisionRank: 3, gp: 3, goals: 6, assists: 5, points: 11, pim: 0 },
  { name: "松本力也", jersey: 14, team: "EUROSPORT MAVIN", divisionLabel: "Platinum", divisionRank: 4, gp: 3, goals: 4, assists: 4, points: 8, pim: 0 },
  { name: "Jackson, Dei Rossi", jersey: 7, team: "Flying Penguins", divisionLabel: "Platinum", divisionRank: 4, gp: 4, goals: 4, assists: 4, points: 8, pim: 0 },
  { name: "石井寛人", jersey: 7, team: "かんだ食堂", divisionLabel: "Platinum", divisionRank: 6, gp: 3, goals: 5, assists: 2, points: 7, pim: 0 },
  { name: "松原優太", jersey: 11, team: "Flying Penguins", divisionLabel: "Platinum", divisionRank: 7, gp: 4, goals: 4, assists: 2, points: 6, pim: 0 },
  { name: "町野広光", jersey: 74, team: "Flying Penguins", divisionLabel: "Platinum", divisionRank: 7, gp: 4, goals: 4, assists: 2, points: 6, pim: 0 },
  { name: "和田澪", jersey: 10, team: "かんだ食堂", divisionLabel: "Platinum", divisionRank: 7, gp: 3, goals: 4, assists: 2, points: 6, pim: 0 },
  { name: "坂下孟徳", jersey: 90, team: "かんだ食堂", divisionLabel: "Platinum", divisionRank: 7, gp: 3, goals: 3, assists: 3, points: 6, pim: 0 },
  { name: "石井健人", jersey: 23, team: "かんだ食堂", divisionLabel: "Platinum", divisionRank: 11, gp: 3, goals: 3, assists: 2, points: 5, pim: 0 },
  { name: "一條健太郎", jersey: 11, team: "EUROSPORT MAVIN", divisionLabel: "Platinum", divisionRank: 11, gp: 3, goals: 2, assists: 3, points: 5, pim: 0 },
  { name: "Tyler, Parnell", jersey: 77, team: "Flying Penguins", divisionLabel: "Platinum", divisionRank: 11, gp: 4, goals: 2, assists: 3, points: 5, pim: 0 },
  { name: "佐藤育也", jersey: 15, team: "かんだ食堂", divisionLabel: "Platinum", divisionRank: 14, gp: 3, goals: 3, assists: 1, points: 4, pim: 0 },
  { name: "塩原将志", jersey: 33, team: "Flying Penguins", divisionLabel: "Platinum", divisionRank: 14, gp: 4, goals: 2, assists: 2, points: 4, pim: 0 },
  { name: "林寛和", jersey: 77, team: "Flying Penguins", divisionLabel: "Platinum", divisionRank: 14, gp: 4, goals: 2, assists: 2, points: 4, pim: 0 },
  { name: "羽田野哲志", jersey: 30, team: "EUROSPORT MAVIN", divisionLabel: "Platinum", divisionRank: 17, gp: 3, goals: 2, assists: 1, points: 3, pim: 0 },
  { name: "井手隆弘", jersey: 13, team: "Flying Penguins", divisionLabel: "Platinum", divisionRank: 17, gp: 4, goals: 2, assists: 1, points: 3, pim: 0 },
  { name: "松谷俊輔", jersey: 83, team: "かんだ食堂", divisionLabel: "Platinum", divisionRank: 17, gp: 3, goals: 1, assists: 2, points: 3, pim: 0 },
  { name: "鈴木翔也", jersey: 66, team: "EUROSPORT MAVIN", divisionLabel: "Platinum", divisionRank: 20, gp: 3, goals: 2, assists: 0, points: 2, pim: 0 },
  { name: "鈴木大智", jersey: 77, team: "EUROSPORT MAVIN", divisionLabel: "Platinum", divisionRank: 20, gp: 3, goals: 1, assists: 1, points: 2, pim: 2 },
  { name: "山本涼", jersey: 86, team: "EUROSPORT MAVIN", divisionLabel: "Platinum", divisionRank: 22, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "Timo, Glossman", jersey: 94, team: "EUROSPORT MAVIN", divisionLabel: "Platinum", divisionRank: 22, gp: 3, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "高山智宏", jersey: 4, team: "SONIDO", divisionLabel: "Gold", divisionRank: 1, gp: 3, goals: 8, assists: 15, points: 23, pim: 0 },
  { name: "石渡逸成", jersey: 9, team: "SONIDO", divisionLabel: "Gold", divisionRank: 2, gp: 3, goals: 8, assists: 6, points: 14, pim: 0 },
  { name: "叶多洸大", jersey: 61, team: "SONIDO", divisionLabel: "Gold", divisionRank: 3, gp: 3, goals: 5, assists: 6, points: 11, pim: 0 },
  { name: "Jackson, Dei Rossi", jersey: 7, team: "SONIDO", divisionLabel: "Gold", divisionRank: 4, gp: 3, goals: 6, assists: 4, points: 10, pim: 0 },
  { name: "須藤水晶", jersey: 20, team: "Primo Terra", divisionLabel: "Gold", divisionRank: 5, gp: 2, goals: 4, assists: 2, points: 6, pim: 0 },
  { name: "谷平陽祐", jersey: 60, team: "Primo Terra", divisionLabel: "Gold", divisionRank: 5, gp: 2, goals: 4, assists: 2, points: 6, pim: 0 },
  { name: "Tyler, Parnell", jersey: 58, team: "SONIDO", divisionLabel: "Gold", divisionRank: 7, gp: 3, goals: 5, assists: 0, points: 5, pim: 0 },
  { name: "坂下孟徳", jersey: 90, team: "DROP HAMMER", divisionLabel: "Gold", divisionRank: 7, gp: 3, goals: 4, assists: 1, points: 5, pim: 0 },
  { name: "塩原将志", jersey: 33, team: "SONIDO", divisionLabel: "Gold", divisionRank: 7, gp: 3, goals: 4, assists: 1, points: 5, pim: 0 },
  { name: "和田澪", jersey: 10, team: "DROP HAMMER", divisionLabel: "Gold", divisionRank: 7, gp: 3, goals: 2, assists: 3, points: 5, pim: 0 },
  { name: "林寛和", jersey: 61, team: "SONIDO", divisionLabel: "Gold", divisionRank: 11, gp: 3, goals: 3, assists: 1, points: 4, pim: 0 },
  { name: "山崎悠作", jersey: 5, team: "DROP HAMMER", divisionLabel: "Gold", divisionRank: 12, gp: 3, goals: 3, assists: 0, points: 3, pim: 0 },
  { name: "松谷俊輔", jersey: 83, team: "DROP HAMMER", divisionLabel: "Gold", divisionRank: 12, gp: 3, goals: 2, assists: 1, points: 3, pim: 0 },
  { name: "町野広光", jersey: 26, team: "DROP HAMMER", divisionLabel: "Gold", divisionRank: 12, gp: 3, goals: 1, assists: 2, points: 3, pim: 0 },
  { name: "松原優太", jersey: 29, team: "DROP HAMMER", divisionLabel: "Gold", divisionRank: 12, gp: 3, goals: 1, assists: 2, points: 3, pim: 0 },
  { name: "石川滉太", jersey: 24, team: "DROP HAMMER", divisionLabel: "Gold", divisionRank: 16, gp: 3, goals: 1, assists: 1, points: 2, pim: 0 },
  { name: "内海基成", jersey: 3, team: "Primo Terra", divisionLabel: "Gold", divisionRank: 16, gp: 2, goals: 1, assists: 1, points: 2, pim: 0 },
  { name: "Timoty, Grossmann", jersey: 60, team: "Primo Terra", divisionLabel: "Gold", divisionRank: 16, gp: 2, goals: 1, assists: 1, points: 2, pim: 0 },
  { name: "新山公太郎", jersey: 68, team: "DROP HAMMER", divisionLabel: "Gold", divisionRank: 19, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "馬場健悟", jersey: 50, team: "Primo Terra", divisionLabel: "Gold", divisionRank: 19, gp: 2, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "高山智宏", jersey: 4, team: "Flying Penguins Silver", divisionLabel: "Silver", divisionRank: 1, gp: 3, goals: 8, assists: 17, points: 25, pim: 0 },
  { name: "石渡逸成", jersey: 14, team: "STIGA Silver", divisionLabel: "Silver", divisionRank: 2, gp: 3, goals: 5, assists: 13, points: 18, pim: 2 },
  { name: "谷平陽祐", jersey: 78, team: "STIGA Silver", divisionLabel: "Silver", divisionRank: 3, gp: 3, goals: 11, assists: 4, points: 15, pim: 0 },
  { name: "町野広光", jersey: 74, team: "Flying Penguins Silver", divisionLabel: "Silver", divisionRank: 4, gp: 3, goals: 11, assists: 1, points: 12, pim: 0 },
  { name: "石井健人", jersey: 23, team: "ダイナモ 2nd", divisionLabel: "Silver", divisionRank: 5, gp: 4, goals: 5, assists: 4, points: 9, pim: 0 },
  { name: "山崎悠作", jersey: 5, team: "ダイナモ 2nd", divisionLabel: "Silver", divisionRank: 6, gp: 4, goals: 5, assists: 3, points: 8, pim: 0 },
  { name: "末廣空大", jersey: 46, team: "ダイナモ 2nd", divisionLabel: "Silver", divisionRank: 6, gp: 4, goals: 3, assists: 5, points: 8, pim: 0 },
  { name: "森田真由", jersey: 93, team: "Flying Penguins Silver", divisionLabel: "Silver", divisionRank: 8, gp: 3, goals: 4, assists: 3, points: 7, pim: 0 },
  { name: "新山公太郎", jersey: 44, team: "SYGMA", divisionLabel: "Silver", divisionRank: 8, gp: 3, goals: 3, assists: 4, points: 7, pim: 0 },
  { name: "石川滉太", jersey: 24, team: "ダイナモ 2nd", divisionLabel: "Silver", divisionRank: 8, gp: 4, goals: 3, assists: 4, points: 7, pim: 2 },
  { name: "塩原将志", jersey: 33, team: "Flying Penguins Silver", divisionLabel: "Silver", divisionRank: 11, gp: 3, goals: 5, assists: 1, points: 6, pim: 0 },
  { name: "勅使河原小梅", jersey: 89, team: "SYGMA", divisionLabel: "Silver", divisionRank: 11, gp: 3, goals: 4, assists: 2, points: 6, pim: 0 },
  { name: "音賀優颯", jersey: 9, team: "ダイナモ 2nd", divisionLabel: "Silver", divisionRank: 11, gp: 4, goals: 3, assists: 3, points: 6, pim: 0 },
  { name: "和田澪", jersey: 10, team: "SYGMA", divisionLabel: "Silver", divisionRank: 14, gp: 3, goals: 4, assists: 1, points: 5, pim: 0 },
  { name: "須永宜司", jersey: 2, team: "STIGA Silver", divisionLabel: "Silver", divisionRank: 14, gp: 3, goals: 3, assists: 2, points: 5, pim: 0 },
  { name: "今野詩音", jersey: 12, team: "SYGMA", divisionLabel: "Silver", divisionRank: 14, gp: 3, goals: 3, assists: 2, points: 5, pim: 0 },
  { name: "川嶋晃太朗", jersey: 15, team: "SYGMA", divisionLabel: "Silver", divisionRank: 14, gp: 3, goals: 3, assists: 2, points: 5, pim: 2 },
  { name: "叶多洸大", jersey: 44, team: "SYGMA", divisionLabel: "Silver", divisionRank: 14, gp: 3, goals: 2, assists: 3, points: 5, pim: 0 },
  { name: "小池望愛", jersey: 82, team: "SYGMA", divisionLabel: "Silver", divisionRank: 14, gp: 3, goals: 2, assists: 3, points: 5, pim: 0 },
  { name: "坂下孟徳", jersey: 90, team: "ダイナモ", divisionLabel: "Silver", divisionRank: 20, gp: 3, goals: 3, assists: 1, points: 4, pim: 0 },
  { name: "是澤咲良", jersey: 16, team: "Flying Penguins Silver", divisionLabel: "Silver", divisionRank: 20, gp: 3, goals: 2, assists: 2, points: 4, pim: 0 },
  { name: "石毛力", jersey: 5, team: "SYGMA", divisionLabel: "Silver", divisionRank: 20, gp: 3, goals: 2, assists: 2, points: 4, pim: 0 },
  { name: "松岡侑依", jersey: 90, team: "SYGMA", divisionLabel: "Silver", divisionRank: 20, gp: 3, goals: 1, assists: 3, points: 4, pim: 0 },
  { name: "Tyler, Parnell", jersey: 58, team: "STIGA Silver", divisionLabel: "Silver", divisionRank: 24, gp: 3, goals: 3, assists: 0, points: 3, pim: 0 },
  { name: "伊原克将", jersey: 49, team: "STIGA Silver", divisionLabel: "Silver", divisionRank: 24, gp: 3, goals: 3, assists: 0, points: 3, pim: 0 },
  { name: "Jackson, Dei Rossi", jersey: 7, team: "NRK", divisionLabel: "Silver", divisionRank: 24, gp: 3, goals: 2, assists: 1, points: 3, pim: 0 },
  { name: "林寛和", jersey: 77, team: "Flying Penguins Silver", divisionLabel: "Silver", divisionRank: 24, gp: 3, goals: 1, assists: 2, points: 3, pim: 0 },
  { name: "須藤水晶", jersey: 50, team: "STIGA Silver", divisionLabel: "Silver", divisionRank: 24, gp: 3, goals: 1, assists: 2, points: 3, pim: 2 },
  { name: "角丸貴洋", jersey: 62, team: "STIGA Silver", divisionLabel: "Silver", divisionRank: 24, gp: 3, goals: 1, assists: 2, points: 3, pim: 0 },
  { name: "井手隆弘", jersey: 14, team: "SYGMA", divisionLabel: "Silver", divisionRank: 24, gp: 3, goals: 1, assists: 2, points: 3, pim: 0 },
  { name: "国分竜也", jersey: 36, team: "ダイナモ 2nd", divisionLabel: "Silver", divisionRank: 24, gp: 4, goals: 1, assists: 2, points: 3, pim: 0 },
  { name: "大田素義", jersey: 17, team: "名無しBoyz Starz", divisionLabel: "Silver", divisionRank: 24, gp: 3, goals: 1, assists: 2, points: 3, pim: 0 },
  { name: "勝野貴志", jersey: 75, team: "STIGA Silver", divisionLabel: "Silver", divisionRank: 33, gp: 3, goals: 2, assists: 0, points: 2, pim: 0 },
  { name: "市川勇午", jersey: 77, team: "ダイナモ", divisionLabel: "Silver", divisionRank: 33, gp: 3, goals: 2, assists: 0, points: 2, pim: 0 },
  { name: "時田克彦", jersey: 90, team: "ダイナモ 2nd", divisionLabel: "Silver", divisionRank: 33, gp: 4, goals: 2, assists: 0, points: 2, pim: 0 },
  { name: "太田, Dennis", jersey: 19, team: "名無しBoyz Starz", divisionLabel: "Silver", divisionRank: 33, gp: 3, goals: 2, assists: 0, points: 2, pim: 0 },
  { name: "早尾理沙", jersey: 37, team: "SYGMA", divisionLabel: "Silver", divisionRank: 33, gp: 3, goals: 1, assists: 1, points: 2, pim: 0 },
  { name: "上田大輔", jersey: 68, team: "名無しBoyz Starz", divisionLabel: "Silver", divisionRank: 33, gp: 3, goals: 1, assists: 1, points: 2, pim: 0 },
  { name: "木原奈々子", jersey: 96, team: "Flying Penguins Silver", divisionLabel: "Silver", divisionRank: 39, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "白谷友和", jersey: 16, team: "NRK", divisionLabel: "Silver", divisionRank: 39, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "鴻嶋萌々香", jersey: 4, team: "NRK", divisionLabel: "Silver", divisionRank: 39, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "Timo, Grossmann", jersey: 99, team: "NRK", divisionLabel: "Silver", divisionRank: 39, gp: 3, goals: 1, assists: 0, points: 1, pim: 2 },
  { name: "榊勢那", jersey: 19, team: "STIGA Silver", divisionLabel: "Silver", divisionRank: 39, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "馬場健吾", jersey: 19, team: "ダイナモ", divisionLabel: "Silver", divisionRank: 39, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "相原寛大", jersey: 14, team: "ダイナモ", divisionLabel: "Silver", divisionRank: 39, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "松原優太", jersey: 29, team: "ダイナモ", divisionLabel: "Silver", divisionRank: 39, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "小林壮", jersey: 32, team: "ダイナモ 2nd", divisionLabel: "Silver", divisionRank: 39, gp: 4, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "Cheng, Andy", jersey: 3, team: "名無しBoyz Starz", divisionLabel: "Silver", divisionRank: 39, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "田中康寛", jersey: 48, team: "名無しBoyz Starz", divisionLabel: "Silver", divisionRank: 39, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "井手隆弘", jersey: 92, team: "名無しBoyz Starz", divisionLabel: "Silver", divisionRank: 39, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "渡部晴樹", jersey: 22, team: "NRK", divisionLabel: "Silver", divisionRank: 39, gp: 3, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "久保田一誠", jersey: 7, team: "ダイナモ", divisionLabel: "Silver", divisionRank: 39, gp: 3, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "Emarson, Keung", jersey: 73, team: "ダイナモ 2nd", divisionLabel: "Silver", divisionRank: 39, gp: 4, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "須藤水晶", jersey: 50, team: "STIGA Bronze", divisionLabel: "Bronze", divisionRank: 1, gp: 3, goals: 10, assists: 10, points: 20, pim: 4 },
  { name: "谷平陽祐", jersey: 78, team: "STIGA Bronze", divisionLabel: "Bronze", divisionRank: 2, gp: 3, goals: 13, assists: 3, points: 16, pim: 0 },
  { name: "勅使川原小梅", jersey: 89, team: "日体大DREAMS", divisionLabel: "Bronze", divisionRank: 3, gp: 3, goals: 6, assists: 8, points: 14, pim: 0 },
  { name: "相原寛太", jersey: 6, team: "日体大DREAMS", divisionLabel: "Bronze", divisionRank: 4, gp: 3, goals: 6, assists: 5, points: 11, pim: 0 },
  { name: "石毛力", jersey: 90, team: "Millennium Falcons", divisionLabel: "Bronze", divisionRank: 5, gp: 3, goals: 7, assists: 0, points: 7, pim: 0 },
  { name: "小池望愛", jersey: 98, team: "日体大DREAMS", divisionLabel: "Bronze", divisionRank: 5, gp: 3, goals: 5, assists: 2, points: 7, pim: 0 },
  { name: "白谷友和", jersey: 16, team: "サイコペッカーズ", divisionLabel: "Bronze", divisionRank: 5, gp: 3, goals: 3, assists: 4, points: 7, pim: 2 },
  { name: "鈴木璃音", jersey: 14, team: "RASTAS", divisionLabel: "Bronze", divisionRank: 8, gp: 2, goals: 5, assists: 1, points: 6, pim: 0 },
  { name: "和田真之介", jersey: 91, team: "WHITE WOLF", divisionLabel: "Bronze", divisionRank: 8, gp: 2, goals: 5, assists: 1, points: 6, pim: 0 },
  { name: "宇都木友樹", jersey: 9, team: "WHITE WOLF", divisionLabel: "Bronze", divisionRank: 8, gp: 2, goals: 4, assists: 2, points: 6, pim: 0 },
  { name: "角丸貴洋", jersey: 19, team: "STIGA Bronze", divisionLabel: "Bronze", divisionRank: 11, gp: 3, goals: 5, assists: 0, points: 5, pim: 2 },
  { name: "師岡海", jersey: 24, team: "サイコペッカーズ", divisionLabel: "Bronze", divisionRank: 11, gp: 3, goals: 4, assists: 1, points: 5, pim: 0 },
  { name: "大田素義", jersey: 17, team: "名無しBoyzⅡ", divisionLabel: "Bronze", divisionRank: 11, gp: 2, goals: 4, assists: 1, points: 5, pim: 0 },
  { name: "森悠", jersey: 5, team: "サイコペッカーズ", divisionLabel: "Bronze", divisionRank: 11, gp: 3, goals: 3, assists: 2, points: 5, pim: 0 },
  { name: "国分竜也", jersey: 11, team: "フライングペンギンズM", divisionLabel: "Bronze", divisionRank: 11, gp: 3, goals: 3, assists: 2, points: 5, pim: 0 },
  { name: "Cheng, Andy", jersey: 3, team: "名無しBoyzⅡ", divisionLabel: "Bronze", divisionRank: 11, gp: 2, goals: 2, assists: 3, points: 5, pim: 0 },
  { name: "伊原克将", jersey: 49, team: "Millennium Falcons", divisionLabel: "Bronze", divisionRank: 11, gp: 3, goals: 1, assists: 4, points: 5, pim: 0 },
  { name: "八藤信幸", jersey: 80, team: "サイコペッカーズ", divisionLabel: "Bronze", divisionRank: 18, gp: 3, goals: 4, assists: 0, points: 4, pim: 2 },
  { name: "末廣空大", jersey: 96, team: "日体大DREAMS", divisionLabel: "Bronze", divisionRank: 18, gp: 3, goals: 3, assists: 1, points: 4, pim: 0 },
  { name: "松島宏記", jersey: 39, team: "RASTAS", divisionLabel: "Bronze", divisionRank: 18, gp: 2, goals: 2, assists: 2, points: 4, pim: 0 },
  { name: "上田大輔", jersey: 68, team: "サイコペッカーズ", divisionLabel: "Bronze", divisionRank: 18, gp: 3, goals: 2, assists: 2, points: 4, pim: 0 },
  { name: "田中康寛", jersey: 48, team: "名無しBoyzⅡ", divisionLabel: "Bronze", divisionRank: 18, gp: 2, goals: 2, assists: 2, points: 4, pim: 0 },
  { name: "馬場健吾", jersey: 18, team: "Dark sales", divisionLabel: "Bronze", divisionRank: 18, gp: 2, goals: 1, assists: 3, points: 4, pim: 0 },
  { name: "松岡徹", jersey: 10, team: "WHITE WOLF", divisionLabel: "Bronze", divisionRank: 18, gp: 2, goals: 1, assists: 3, points: 4, pim: 0 },
  { name: "小林壮", jersey: 93, team: "Dark sales", divisionLabel: "Bronze", divisionRank: 25, gp: 2, goals: 3, assists: 0, points: 3, pim: 2 },
  { name: "市川勇午", jersey: 88, team: "Dark sales", divisionLabel: "Bronze", divisionRank: 25, gp: 2, goals: 3, assists: 0, points: 3, pim: 0 },
  { name: "向井悠", jersey: 3, team: "Millennium Falcons", divisionLabel: "Bronze", divisionRank: 25, gp: 3, goals: 3, assists: 0, points: 3, pim: 0 },
  { name: "音賀優颯", jersey: 91, team: "RASTAS", divisionLabel: "Bronze", divisionRank: 25, gp: 2, goals: 3, assists: 0, points: 3, pim: 0 },
  { name: "落合芳明", jersey: 28, team: "WHITE WOLF", divisionLabel: "Bronze", divisionRank: 25, gp: 2, goals: 3, assists: 0, points: 3, pim: 0 },
  { name: "Mitchell, Kevin", jersey: 18, team: "名無しBoyzⅡ", divisionLabel: "Bronze", divisionRank: 25, gp: 2, goals: 3, assists: 0, points: 3, pim: 0 },
  { name: "増田悠里", jersey: 97, team: "名無しBoyzⅡ", divisionLabel: "Bronze", divisionRank: 25, gp: 2, goals: 3, assists: 0, points: 3, pim: 0 },
  { name: "鈴木規之", jersey: 88, team: "RASTAS", divisionLabel: "Bronze", divisionRank: 25, gp: 2, goals: 2, assists: 1, points: 3, pim: 0 },
  { name: "錦戸大", jersey: 55, team: "サイコペッカーズ", divisionLabel: "Bronze", divisionRank: 25, gp: 3, goals: 2, assists: 1, points: 3, pim: 0 },
  { name: "大森天翔", jersey: 2, team: "フライングペンギンズM", divisionLabel: "Bronze", divisionRank: 25, gp: 3, goals: 2, assists: 1, points: 3, pim: 0 },
  { name: "浪本雅和", jersey: 79, team: "RASTAS", divisionLabel: "Bronze", divisionRank: 25, gp: 2, goals: 1, assists: 2, points: 3, pim: 2 },
  { name: "沢田真奈巳", jersey: 19, team: "WHITE WOLF", divisionLabel: "Bronze", divisionRank: 25, gp: 2, goals: 1, assists: 2, points: 3, pim: 0 },
  { name: "奥垣内小太郎", jersey: 30, team: "日体大DREAMS", divisionLabel: "Bronze", divisionRank: 25, gp: 3, goals: 1, assists: 2, points: 3, pim: 0 },
  { name: "橋本慎之介", jersey: 84, team: "RASTAS", divisionLabel: "Bronze", divisionRank: 25, gp: 2, goals: 0, assists: 3, points: 3, pim: 0 },
  { name: "若林孝一", jersey: 51, team: "Millennium Falcons", divisionLabel: "Bronze", divisionRank: 39, gp: 3, goals: 2, assists: 0, points: 2, pim: 2 },
  { name: "小林英史", jersey: 34, team: "noboundarys", divisionLabel: "Bronze", divisionRank: 39, gp: 3, goals: 2, assists: 0, points: 2, pim: 2 },
  { name: "榊勢那", jersey: 19, team: "STIGA Bronze", divisionLabel: "Bronze", divisionRank: 39, gp: 3, goals: 2, assists: 0, points: 2, pim: 2 },
  { name: "横澤正信", jersey: 8, team: "サイコペッカーズ", divisionLabel: "Bronze", divisionRank: 39, gp: 3, goals: 2, assists: 0, points: 2, pim: 0 },
  { name: "松岡侑依", jersey: 32, team: "フライングペンギンズM", divisionLabel: "Bronze", divisionRank: 39, gp: 3, goals: 2, assists: 0, points: 2, pim: 2 },
  { name: "石川滉太", jersey: 96, team: "フライングペンギンズM", divisionLabel: "Bronze", divisionRank: 39, gp: 3, goals: 2, assists: 0, points: 2, pim: 2 },
  { name: "関谷勇吹", jersey: 17, team: "フライングペンギンズM", divisionLabel: "Bronze", divisionRank: 39, gp: 3, goals: 1, assists: 1, points: 2, pim: 4 },
  { name: "鴻嶋萌々香", jersey: 39, team: "日体大DREAMS", divisionLabel: "Bronze", divisionRank: 39, gp: 3, goals: 1, assists: 1, points: 2, pim: 0 },
  { name: "田中優也", jersey: 5, team: "名無しBoyzⅡ", divisionLabel: "Bronze", divisionRank: 39, gp: 2, goals: 0, assists: 2, points: 2, pim: 0 },
  { name: "伍井岳", jersey: 51, team: "名無しBoyzⅡ", divisionLabel: "Bronze", divisionRank: 39, gp: 2, goals: 0, assists: 2, points: 2, pim: 2 },
  { name: "石川滉太", jersey: 8, team: "Dark sales", divisionLabel: "Bronze", divisionRank: 49, gp: 2, goals: 1, assists: 0, points: 1, pim: 2 },
  { name: "堤千明", jersey: 21, team: "noboundarys", divisionLabel: "Bronze", divisionRank: 49, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "竹内寧", jersey: 84, team: "noboundarys", divisionLabel: "Bronze", divisionRank: 49, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "小鷹章宏", jersey: 23, team: "noboundarys", divisionLabel: "Bronze", divisionRank: 49, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "久保壮史", jersey: 24, team: "noboundarys", divisionLabel: "Bronze", divisionRank: 49, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "梅原広規", jersey: 10, team: "noboundarys", divisionLabel: "Bronze", divisionRank: 49, gp: 3, goals: 1, assists: 0, points: 1, pim: 2 },
  { name: "宮城努", jersey: 10, team: "STIGA Bronze", divisionLabel: "Bronze", divisionRank: 49, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "坂田哲也", jersey: 23, team: "フライングペンギンズM", divisionLabel: "Bronze", divisionRank: 49, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "太田, Dennis", jersey: 19, team: "名無しBoyzⅡ", divisionLabel: "Bronze", divisionRank: 49, gp: 2, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "森田真由", jersey: 95, team: "Dark sales", divisionLabel: "Bronze", divisionRank: 49, gp: 2, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "宇野加恒哉", jersey: 82, team: "Dark sales", divisionLabel: "Bronze", divisionRank: 49, gp: 2, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "佐伯かりん", jersey: 14, team: "Dark sales", divisionLabel: "Bronze", divisionRank: 49, gp: 2, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "小川修平", jersey: 13, team: "Millennium Falcons", divisionLabel: "Bronze", divisionRank: 49, gp: 3, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "斎藤利一", jersey: 36, team: "noboundarys", divisionLabel: "Bronze", divisionRank: 49, gp: 3, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "生井健介", jersey: 31, team: "STIGA Bronze", divisionLabel: "Bronze", divisionRank: 49, gp: 3, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "西村亮平", jersey: 3, team: "STIGA Bronze", divisionLabel: "Bronze", divisionRank: 49, gp: 3, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "今西善徳", jersey: 5, team: "WHITE WOLF", divisionLabel: "Bronze", divisionRank: 49, gp: 2, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "金成俊彦", jersey: 67, team: "名無しBoyzⅡ", divisionLabel: "Bronze", divisionRank: 49, gp: 2, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "駒木根大輔", jersey: 10, team: "サイコ", divisionLabel: "Brass", divisionRank: 1, gp: 4, goals: 11, assists: 4, points: 15, pim: 0 },
  { name: "音賀優颯", jersey: 9, team: "風神雷神", divisionLabel: "Brass", divisionRank: 2, gp: 3, goals: 10, assists: 3, points: 13, pim: 0 },
  { name: "下平晃", jersey: 18, team: "Abouters", divisionLabel: "Brass", divisionRank: 2, gp: 4, goals: 5, assists: 8, points: 13, pim: 0 },
  { name: "榊勢那", jersey: 19, team: "Abouters", divisionLabel: "Brass", divisionRank: 4, gp: 4, goals: 10, assists: 2, points: 12, pim: 0 },
  { name: "伊原克将", jersey: 49, team: "Evolving Discus", divisionLabel: "Brass", divisionRank: 5, gp: 3, goals: 6, assists: 5, points: 11, pim: 0 },
  { name: "久保田一誠", jersey: 4, team: "Team Apples", divisionLabel: "Brass", divisionRank: 5, gp: 3, goals: 6, assists: 5, points: 11, pim: 0 },
  { name: "大田素義", jersey: 17, team: "名無しBoyz", divisionLabel: "Brass", divisionRank: 7, gp: 4, goals: 8, assists: 2, points: 10, pim: 0 },
  { name: "宮城努", jersey: 10, team: "Abouters", divisionLabel: "Brass", divisionRank: 8, gp: 4, goals: 5, assists: 3, points: 8, pim: 0 },
  { name: "森悠", jersey: 5, team: "サイコ", divisionLabel: "Brass", divisionRank: 8, gp: 4, goals: 5, assists: 3, points: 8, pim: 0 },
  { name: "横澤正信", jersey: 8, team: "サイコ", divisionLabel: "Brass", divisionRank: 8, gp: 4, goals: 3, assists: 5, points: 8, pim: 0 },
  { name: "森田剛仁", jersey: 2, team: "名無しBoyz", divisionLabel: "Brass", divisionRank: 8, gp: 4, goals: 2, assists: 6, points: 8, pim: 0 },
  { name: "若林孝一", jersey: 51, team: "Evolving Discus", divisionLabel: "Brass", divisionRank: 12, gp: 3, goals: 5, assists: 2, points: 7, pim: 0 },
  { name: "田井智晴", jersey: 42, team: "Team Apples", divisionLabel: "Brass", divisionRank: 12, gp: 3, goals: 5, assists: 2, points: 7, pim: 0 },
  { name: "小島竜士", jersey: 22, team: "Abouters", divisionLabel: "Brass", divisionRank: 12, gp: 4, goals: 4, assists: 3, points: 7, pim: 0 },
  { name: "Cheng, Andy", jersey: 8, team: "NASDAQ", divisionLabel: "Brass", divisionRank: 12, gp: 3, goals: 4, assists: 3, points: 7, pim: 4 },
  { name: "八藤信幸", jersey: 80, team: "サイコ", divisionLabel: "Brass", divisionRank: 12, gp: 4, goals: 3, assists: 4, points: 7, pim: 0 },
  { name: "及部拓人", jersey: 7, team: "EarlyBird", divisionLabel: "Brass", divisionRank: 17, gp: 4, goals: 5, assists: 1, points: 6, pim: 0 },
  { name: "国分竜也", jersey: 84, team: "Team Apples", divisionLabel: "Brass", divisionRank: 17, gp: 3, goals: 5, assists: 1, points: 6, pim: 0 },
  { name: "坂田哲也", jersey: 23, team: "EarlyBird", divisionLabel: "Brass", divisionRank: 17, gp: 4, goals: 3, assists: 3, points: 6, pim: 0 },
  { name: "増田勝喜", jersey: 99, team: "風神雷神", divisionLabel: "Brass", divisionRank: 17, gp: 3, goals: 2, assists: 4, points: 6, pim: 0 },
  { name: "今井田侑樹", jersey: 8, team: "Team Apples", divisionLabel: "Brass", divisionRank: 17, gp: 3, goals: 1, assists: 5, points: 6, pim: 0 },
  { name: "小室康平", jersey: 13, team: "風神雷神", divisionLabel: "Brass", divisionRank: 22, gp: 3, goals: 4, assists: 1, points: 5, pim: 0 },
  { name: "小池望愛", jersey: 14, team: "WSJ", divisionLabel: "Brass", divisionRank: 22, gp: 4, goals: 3, assists: 2, points: 5, pim: 0 },
  { name: "斉藤利一", jersey: 36, team: "EarlyBird", divisionLabel: "Brass", divisionRank: 22, gp: 4, goals: 2, assists: 3, points: 5, pim: 2 },
  { name: "佐伯かりん", jersey: 4, team: "WSJ", divisionLabel: "Brass", divisionRank: 22, gp: 4, goals: 2, assists: 3, points: 5, pim: 0 },
  { name: "田中康寛", jersey: 48, team: "名無しBoyz", divisionLabel: "Brass", divisionRank: 22, gp: 4, goals: 2, assists: 3, points: 5, pim: 2 },
  { name: "相原寛大", jersey: 4, team: "Individuals Brass", divisionLabel: "Brass", divisionRank: 27, gp: 3, goals: 3, assists: 1, points: 4, pim: 0 },
  { name: "塩野谷綾", jersey: 2, team: "WSJ", divisionLabel: "Brass", divisionRank: 27, gp: 4, goals: 3, assists: 1, points: 4, pim: 0 },
  { name: "奥津七海", jersey: 7, team: "WSJ", divisionLabel: "Brass", divisionRank: 27, gp: 4, goals: 3, assists: 1, points: 4, pim: 0 },
  { name: "松岡侑依", jersey: 3, team: "WSJ", divisionLabel: "Brass", divisionRank: 27, gp: 4, goals: 3, assists: 1, points: 4, pim: 0 },
  { name: "田中優也", jersey: 5, team: "名無しBoyz", divisionLabel: "Brass", divisionRank: 27, gp: 4, goals: 3, assists: 1, points: 4, pim: 0 },
  { name: "綿貫敦記", jersey: 91, team: "EarlyBird", divisionLabel: "Brass", divisionRank: 27, gp: 4, goals: 2, assists: 2, points: 4, pim: 0 },
  { name: "中村裕之", jersey: 88, team: "NASDAQ", divisionLabel: "Brass", divisionRank: 27, gp: 3, goals: 2, assists: 2, points: 4, pim: 0 },
  { name: "木原奈々子", jersey: 52, team: "Team Apples", divisionLabel: "Brass", divisionRank: 27, gp: 3, goals: 2, assists: 2, points: 4, pim: 0 },
  { name: "内田亮宏", jersey: 21, team: "サイコ", divisionLabel: "Brass", divisionRank: 27, gp: 4, goals: 2, assists: 2, points: 4, pim: 2 },
  { name: "田川義延", jersey: 3, team: "風神雷神", divisionLabel: "Brass", divisionRank: 27, gp: 3, goals: 2, assists: 2, points: 4, pim: 0 },
  { name: "Van Ackere, Michel", jersey: 44, team: "名無しBoyz", divisionLabel: "Brass", divisionRank: 27, gp: 4, goals: 1, assists: 3, points: 4, pim: 2 },
  { name: "森田潤", jersey: 11, team: "Abouters", divisionLabel: "Brass", divisionRank: 38, gp: 4, goals: 3, assists: 0, points: 3, pim: 2 },
  { name: "谷口泰久", jersey: 84, team: "EarlyBird", divisionLabel: "Brass", divisionRank: 38, gp: 4, goals: 3, assists: 0, points: 3, pim: 0 },
  { name: "中津祥章", jersey: 21, team: "EarlyBird", divisionLabel: "Brass", divisionRank: 38, gp: 4, goals: 3, assists: 0, points: 3, pim: 0 },
  { name: "榎本盛介", jersey: 89, team: "team TOKO", divisionLabel: "Brass", divisionRank: 38, gp: 3, goals: 3, assists: 0, points: 3, pim: 0 },
  { name: "増田里志", jersey: 96, team: "風神雷神", divisionLabel: "Brass", divisionRank: 38, gp: 3, goals: 3, assists: 0, points: 3, pim: 0 },
  { name: "大岡俊彦", jersey: 35, team: "Evolving Discus", divisionLabel: "Brass", divisionRank: 38, gp: 3, goals: 2, assists: 1, points: 3, pim: 0 },
  { name: "久保龍真", jersey: 90, team: "team TOKO", divisionLabel: "Brass", divisionRank: 38, gp: 3, goals: 2, assists: 1, points: 3, pim: 0 },
  { name: "師岡海", jersey: 24, team: "サイコ", divisionLabel: "Brass", divisionRank: 38, gp: 4, goals: 2, assists: 1, points: 3, pim: 0 },
  { name: "牧野統", jersey: 1, team: "サイコ", divisionLabel: "Brass", divisionRank: 38, gp: 4, goals: 2, assists: 1, points: 3, pim: 0 },
  { name: "小林英史", jersey: 82, team: "Evolving Discus", divisionLabel: "Brass", divisionRank: 38, gp: 3, goals: 1, assists: 2, points: 3, pim: 0 },
  { name: "市川勇午", jersey: 8, team: "Individuals Brass", divisionLabel: "Brass", divisionRank: 38, gp: 3, goals: 1, assists: 2, points: 3, pim: 0 },
  { name: "伍井明日香", jersey: 8, team: "WSJ", divisionLabel: "Brass", divisionRank: 38, gp: 4, goals: 0, assists: 3, points: 3, pim: 2 },
  { name: "平野陽介", jersey: 7, team: "Evolving Discus", divisionLabel: "Brass", divisionRank: 50, gp: 3, goals: 2, assists: 0, points: 2, pim: 0 },
  { name: "難波秀庸", jersey: 78, team: "Evolving Discus", divisionLabel: "Brass", divisionRank: 50, gp: 3, goals: 2, assists: 0, points: 2, pim: 0 },
  { name: "末廣空大", jersey: 9, team: "Individuals Brass", divisionLabel: "Brass", divisionRank: 50, gp: 3, goals: 2, assists: 0, points: 2, pim: 0 },
  { name: "戸井田拓", jersey: 61, team: "Team Apples", divisionLabel: "Brass", divisionRank: 50, gp: 3, goals: 2, assists: 0, points: 2, pim: 0 },
  { name: "片平晋吾", jersey: 39, team: "team TOKO", divisionLabel: "Brass", divisionRank: 50, gp: 3, goals: 2, assists: 0, points: 2, pim: 0 },
  { name: "上田大輔", jersey: 68, team: "サイコ", divisionLabel: "Brass", divisionRank: 50, gp: 4, goals: 2, assists: 0, points: 2, pim: 0 },
  { name: "田中登", jersey: 17, team: "サイコ", divisionLabel: "Brass", divisionRank: 50, gp: 4, goals: 2, assists: 0, points: 2, pim: 0 },
  { name: "James, Dennier", jersey: 15, team: "名無しBoyz", divisionLabel: "Brass", divisionRank: 50, gp: 4, goals: 2, assists: 0, points: 2, pim: 0 },
  { name: "齋藤美穂", jersey: 34, team: "NASDAQ", divisionLabel: "Brass", divisionRank: 50, gp: 3, goals: 1, assists: 1, points: 2, pim: 2 },
  { name: "渡部晴樹", jersey: 92, team: "NASDAQ", divisionLabel: "Brass", divisionRank: 50, gp: 3, goals: 1, assists: 1, points: 2, pim: 0 },
  { name: "福嶋俊介", jersey: 62, team: "Team Apples", divisionLabel: "Brass", divisionRank: 50, gp: 3, goals: 1, assists: 1, points: 2, pim: 0 },
  { name: "中村智", jersey: 91, team: "team TOKO", divisionLabel: "Brass", divisionRank: 50, gp: 3, goals: 1, assists: 1, points: 2, pim: 2 },
  { name: "田中優也", jersey: 17, team: "サイコ", divisionLabel: "Brass", divisionRank: 50, gp: 4, goals: 1, assists: 1, points: 2, pim: 0 },
  { name: "Fraser, Steven", jersey: 13, team: "名無しBoyz", divisionLabel: "Brass", divisionRank: 50, gp: 4, goals: 1, assists: 1, points: 2, pim: 0 },
  { name: "Lawson, Damon", jersey: 28, team: "名無しBoyz", divisionLabel: "Brass", divisionRank: 50, gp: 4, goals: 1, assists: 1, points: 2, pim: 2 },
  { name: "橋本健太郎", jersey: 55, team: "team TOKO", divisionLabel: "Brass", divisionRank: 50, gp: 3, goals: 0, assists: 2, points: 2, pim: 0 },
  { name: "田原知典", jersey: 73, team: "風神雷神", divisionLabel: "Brass", divisionRank: 50, gp: 3, goals: 0, assists: 2, points: 2, pim: 0 },
  { name: "小川真一郎", jersey: 19, team: "Abouters", divisionLabel: "Brass", divisionRank: 67, gp: 4, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "田代三太", jersey: 3, team: "Abouters", divisionLabel: "Brass", divisionRank: 67, gp: 4, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "加藤桂史", jersey: 2, team: "EarlyBird", divisionLabel: "Brass", divisionRank: 67, gp: 4, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "増田悠里", jersey: 68, team: "Evolving Discus", divisionLabel: "Brass", divisionRank: 67, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "小林群", jersey: 9, team: "Individuals Brass", divisionLabel: "Brass", divisionRank: 67, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "阿部壮介", jersey: 17, team: "Individuals Brass", divisionLabel: "Brass", divisionRank: 67, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "堤千明", jersey: 21, team: "NASDAQ", divisionLabel: "Brass", divisionRank: 67, gp: 3, goals: 1, assists: 0, points: 1, pim: 2 },
  { name: "高山正清", jersey: 81, team: "team TOKO", divisionLabel: "Brass", divisionRank: 67, gp: 3, goals: 1, assists: 0, points: 1, pim: 2 },
  { name: "??根 碧", jersey: 12, team: "WSJ", divisionLabel: "Brass", divisionRank: 67, gp: 4, goals: 1, assists: 0, points: 1, pim: 2 },
  { name: "岩崎玲", jersey: 0, team: "WSJ", divisionLabel: "Brass", divisionRank: 67, gp: 4, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "小林伸和", jersey: 92, team: "名無しBoyz", divisionLabel: "Brass", divisionRank: 67, gp: 4, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "石井香代子", jersey: 77, team: "Abouters", divisionLabel: "Brass", divisionRank: 67, gp: 4, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "遠藤洋海", jersey: 11, team: "EarlyBird", divisionLabel: "Brass", divisionRank: 67, gp: 4, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "松井裕樹", jersey: 33, team: "Evolving Discus", divisionLabel: "Brass", divisionRank: 67, gp: 3, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "大石麗奈", jersey: 23, team: "NASDAQ", divisionLabel: "Brass", divisionRank: 67, gp: 3, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "是澤咲良", jersey: 11, team: "WSJ", divisionLabel: "Brass", divisionRank: 67, gp: 4, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "錦戸大", jersey: 55, team: "サイコ", divisionLabel: "Brass", divisionRank: 67, gp: 4, goals: 0, assists: 1, points: 1, pim: 2 },
  { name: "植松大介", jersey: 96, team: "NWC", divisionLabel: "Copper", divisionRank: 1, gp: 8, goals: 20, assists: 7, points: 27, pim: 2 },
  { name: "大森天翔", jersey: 93, team: "ブックレインズ", divisionLabel: "Copper", divisionRank: 2, gp: 8, goals: 19, assists: 5, points: 24, pim: 0 },
  { name: "八藤信幸", jersey: 80, team: "change-zero", divisionLabel: "Copper", divisionRank: 3, gp: 8, goals: 12, assists: 7, points: 19, pim: 2 },
  { name: "朝倉嘉彦", jersey: 91, team: "NWC", divisionLabel: "Copper", divisionRank: 4, gp: 8, goals: 8, assists: 7, points: 15, pim: 0 },
  { name: "藤巻峻", jersey: 10, team: "HCNK Copper", divisionLabel: "Copper", divisionRank: 5, gp: 8, goals: 9, assists: 5, points: 14, pim: 0 },
  { name: "草野涼", jersey: 9, team: "HCNK Copper", divisionLabel: "Copper", divisionRank: 5, gp: 8, goals: 7, assists: 7, points: 14, pim: 2 },
  { name: "関谷勇吹", jersey: 74, team: "ブックレインズ", divisionLabel: "Copper", divisionRank: 5, gp: 8, goals: 7, assists: 7, points: 14, pim: 2 },
  { name: "青山周平", jersey: 26, team: "HCNK Copper", divisionLabel: "Copper", divisionRank: 8, gp: 8, goals: 10, assists: 3, points: 13, pim: 2 },
  { name: "若林孝一", jersey: 23, team: "MASSIVE ATTACK", divisionLabel: "Copper", divisionRank: 8, gp: 7, goals: 9, assists: 4, points: 13, pim: 0 },
  { name: "大泉泰志", jersey: 13, team: "ブックレインズ", divisionLabel: "Copper", divisionRank: 10, gp: 8, goals: 6, assists: 6, points: 12, pim: 0 },
  { name: "増田悠里", jersey: 59, team: "change-zero", divisionLabel: "Copper", divisionRank: 11, gp: 8, goals: 9, assists: 2, points: 11, pim: 0 },
  { name: "小宮直樹", jersey: 56, team: "Discus One", divisionLabel: "Copper", divisionRank: 11, gp: 8, goals: 8, assists: 3, points: 11, pim: 2 },
  { name: "東野寿志", jersey: 78, team: "NWC", divisionLabel: "Copper", divisionRank: 11, gp: 8, goals: 6, assists: 5, points: 11, pim: 0 },
  { name: "下平晃", jersey: 51, team: "伊王島観光協会", divisionLabel: "Copper", divisionRank: 14, gp: 6, goals: 6, assists: 4, points: 10, pim: 0 },
  { name: "菊地威吹", jersey: 1, team: "ドラッカーズ", divisionLabel: "Copper", divisionRank: 15, gp: 8, goals: 6, assists: 3, points: 9, pim: 0 },
  { name: "金野敏和", jersey: 27, team: "伊王島観光協会", divisionLabel: "Copper", divisionRank: 15, gp: 6, goals: 6, assists: 3, points: 9, pim: 0 },
  { name: "小楠敦", jersey: 59, team: "伊王島観光協会", divisionLabel: "Copper", divisionRank: 15, gp: 6, goals: 5, assists: 4, points: 9, pim: 0 },
  { name: "平松泰憲", jersey: 22, team: "MASSIVE ATTACK", divisionLabel: "Copper", divisionRank: 15, gp: 7, goals: 3, assists: 6, points: 9, pim: 0 },
  { name: "久保壮史", jersey: 99, team: "伊王島観光協会", divisionLabel: "Copper", divisionRank: 19, gp: 6, goals: 5, assists: 2, points: 7, pim: 0 },
  { name: "中谷寛志", jersey: 10, team: "NWC", divisionLabel: "Copper", divisionRank: 19, gp: 8, goals: 3, assists: 4, points: 7, pim: 0 },
  { name: "奥村智明", jersey: 7, team: "MASSIVE ATTACK", divisionLabel: "Copper", divisionRank: 21, gp: 7, goals: 6, assists: 0, points: 6, pim: 0 },
  { name: "平野陽介", jersey: 44, team: "MASSIVE ATTACK", divisionLabel: "Copper", divisionRank: 21, gp: 7, goals: 5, assists: 1, points: 6, pim: 0 },
  { name: "小林英史", jersey: 82, team: "Discus One", divisionLabel: "Copper", divisionRank: 21, gp: 8, goals: 4, assists: 2, points: 6, pim: 2 },
  { name: "阿部一彬", jersey: 91, team: "ブックレインズ", divisionLabel: "Copper", divisionRank: 21, gp: 8, goals: 4, assists: 2, points: 6, pim: 0 },
  { name: "犬窪健人", jersey: 4, team: "HCNK Copper", divisionLabel: "Copper", divisionRank: 21, gp: 8, goals: 1, assists: 5, points: 6, pim: 2 },
  { name: "谷口泰久", jersey: 84, team: "伊王島観光協会", divisionLabel: "Copper", divisionRank: 21, gp: 6, goals: 1, assists: 5, points: 6, pim: 0 },
  { name: "武居浩輝", jersey: 74, team: "HCNK Copper", divisionLabel: "Copper", divisionRank: 27, gp: 8, goals: 5, assists: 0, points: 5, pim: 2 },
  { name: "田中登", jersey: 22, team: "change-zero", divisionLabel: "Copper", divisionRank: 27, gp: 8, goals: 4, assists: 1, points: 5, pim: 0 },
  { name: "乾正虎", jersey: 51, team: "伊王島観光協会", divisionLabel: "Copper", divisionRank: 27, gp: 6, goals: 3, assists: 2, points: 5, pim: 0 },
  { name: "内田亮宏", jersey: 5, team: "change-zero", divisionLabel: "Copper", divisionRank: 27, gp: 8, goals: 2, assists: 3, points: 5, pim: 0 },
  { name: "金奇鉉", jersey: 9, team: "Discus One", divisionLabel: "Copper", divisionRank: 27, gp: 8, goals: 2, assists: 3, points: 5, pim: 2 },
  { name: "保科伸一", jersey: 2, team: "MASSIVE ATTACK", divisionLabel: "Copper", divisionRank: 27, gp: 7, goals: 2, assists: 3, points: 5, pim: 0 },
  { name: "小城勇人", jersey: 14, team: "NWC", divisionLabel: "Copper", divisionRank: 27, gp: 8, goals: 2, assists: 3, points: 5, pim: 0 },
  { name: "竹山真人", jersey: 66, team: "HCNK Copper", divisionLabel: "Copper", divisionRank: 27, gp: 8, goals: 1, assists: 4, points: 5, pim: 0 },
  { name: "水野浩之", jersey: 21, team: "HCNK Copper", divisionLabel: "Copper", divisionRank: 35, gp: 8, goals: 4, assists: 0, points: 4, pim: 0 },
  { name: "小城章裕", jersey: 17, team: "NWC", divisionLabel: "Copper", divisionRank: 35, gp: 8, goals: 4, assists: 0, points: 4, pim: 0 },
  { name: "宇田幸一", jersey: 21, team: "Discus One", divisionLabel: "Copper", divisionRank: 35, gp: 8, goals: 3, assists: 1, points: 4, pim: 12 },
  { name: "祓川豊", jersey: 72, team: "HCNK Copper", divisionLabel: "Copper", divisionRank: 35, gp: 8, goals: 3, assists: 1, points: 4, pim: 0 },
  { name: "関口匠", jersey: 6, team: "Prairie Dogs", divisionLabel: "Copper", divisionRank: 35, gp: 7, goals: 3, assists: 1, points: 4, pim: 0 },
  { name: "伊藤一樹", jersey: 16, team: "Prairie Dogs", divisionLabel: "Copper", divisionRank: 35, gp: 7, goals: 3, assists: 1, points: 4, pim: 2 },
  { name: "小口遥斗", jersey: 21, team: "ドラッカーズ", divisionLabel: "Copper", divisionRank: 35, gp: 8, goals: 3, assists: 1, points: 4, pim: 0 },
  { name: "乾正樹", jersey: 21, team: "伊王島観光協会", divisionLabel: "Copper", divisionRank: 35, gp: 6, goals: 3, assists: 1, points: 4, pim: 0 },
  { name: "大岡俊彦", jersey: 35, team: "Discus One", divisionLabel: "Copper", divisionRank: 35, gp: 8, goals: 2, assists: 2, points: 4, pim: 0 },
  { name: "溝部千利", jersey: 7, team: "change-zero", divisionLabel: "Copper", divisionRank: 35, gp: 8, goals: 1, assists: 3, points: 4, pim: 0 },
  { name: "増田勝喜", jersey: 13, team: "change-zero", divisionLabel: "Copper", divisionRank: 35, gp: 8, goals: 1, assists: 3, points: 4, pim: 0 },
  { name: "綿貫敦記", jersey: 1, team: "Individuals Copper", divisionLabel: "Copper", divisionRank: 35, gp: 8, goals: 1, assists: 3, points: 4, pim: 0 },
  { name: "橋野光", jersey: 10, team: "Prairie Dogs", divisionLabel: "Copper", divisionRank: 35, gp: 7, goals: 1, assists: 3, points: 4, pim: 0 },
  { name: "阿部壮介", jersey: 65, team: "Individuals Copper", divisionLabel: "Copper", divisionRank: 48, gp: 8, goals: 3, assists: 0, points: 3, pim: 0 },
  { name: "奥垣内小太郎", jersey: 30, team: "ドラッカーズ", divisionLabel: "Copper", divisionRank: 48, gp: 8, goals: 3, assists: 0, points: 3, pim: 0 },
  { name: "対馬颯太朗", jersey: 99, team: "伊王島観光協会", divisionLabel: "Copper", divisionRank: 48, gp: 6, goals: 3, assists: 0, points: 3, pim: 0 },
  { name: "川田孝輔", jersey: 2, team: "ブックレインズ", divisionLabel: "Copper", divisionRank: 48, gp: 8, goals: 2, assists: 1, points: 3, pim: 0 },
  { name: "神谷英司", jersey: 6, team: "ブックレインズ", divisionLabel: "Copper", divisionRank: 48, gp: 8, goals: 2, assists: 1, points: 3, pim: 0 },
  { name: "奥村竜丞", jersey: 26, team: "ブックレインズ", divisionLabel: "Copper", divisionRank: 48, gp: 8, goals: 2, assists: 1, points: 3, pim: 2 },
  { name: "高橋大和", jersey: 37, team: "ドラッカーズ", divisionLabel: "Copper", divisionRank: 48, gp: 8, goals: 1, assists: 2, points: 3, pim: 0 },
  { name: "住田雄一", jersey: 11, team: "伊王島観光協会", divisionLabel: "Copper", divisionRank: 48, gp: 6, goals: 1, assists: 2, points: 3, pim: 0 },
  { name: "阿部陽道", jersey: 86, team: "Individuals Copper", divisionLabel: "Copper", divisionRank: 56, gp: 8, goals: 2, assists: 0, points: 2, pim: 0 },
  { name: "宮崎正弘", jersey: 7, team: "Individuals Copper", divisionLabel: "Copper", divisionRank: 56, gp: 8, goals: 2, assists: 0, points: 2, pim: 2 },
  { name: "山本泰造", jersey: 6, team: "change-zero", divisionLabel: "Copper", divisionRank: 56, gp: 8, goals: 1, assists: 1, points: 2, pim: 2 },
  { name: "笹尾猛", jersey: 7, team: "Individuals Copper", divisionLabel: "Copper", divisionRank: 56, gp: 8, goals: 1, assists: 1, points: 2, pim: 0 },
  { name: "濱田謙太郎", jersey: 56, team: "Prairie Dogs", divisionLabel: "Copper", divisionRank: 56, gp: 7, goals: 1, assists: 1, points: 2, pim: 0 },
  { name: "青木理", jersey: 16, team: "NWC", divisionLabel: "Copper", divisionRank: 56, gp: 8, goals: 0, assists: 2, points: 2, pim: 0 },
  { name: "珠樹伸彦", jersey: 51, team: "Prairie Dogs", divisionLabel: "Copper", divisionRank: 56, gp: 7, goals: 0, assists: 2, points: 2, pim: 0 },
  { name: "松井勇樹", jersey: 33, team: "Discus One", divisionLabel: "Copper", divisionRank: 63, gp: 8, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "西原一紀", jersey: 36, team: "Individuals Copper", divisionLabel: "Copper", divisionRank: 63, gp: 8, goals: 1, assists: 0, points: 1, pim: 2 },
  { name: "梅原広規", jersey: 3, team: "Individuals Copper", divisionLabel: "Copper", divisionRank: 63, gp: 8, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "Steven, Fraser", jersey: 4, team: "Individuals Copper", divisionLabel: "Copper", divisionRank: 63, gp: 8, goals: 1, assists: 0, points: 1, pim: 2 },
  { name: "鹿野一至", jersey: 14, team: "MASSIVE ATTACK", divisionLabel: "Copper", divisionRank: 63, gp: 7, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "山本浩市", jersey: 29, team: "NWC", divisionLabel: "Copper", divisionRank: 63, gp: 8, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "鎌田政行", jersey: 11, team: "NWC", divisionLabel: "Copper", divisionRank: 63, gp: 8, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "杉沢夕子", jersey: 35, team: "Prairie Dogs", divisionLabel: "Copper", divisionRank: 63, gp: 7, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "高橋新吾", jersey: 19, team: "Prairie Dogs", divisionLabel: "Copper", divisionRank: 63, gp: 7, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "湯川隆臣", jersey: 96, team: "ブックレインズ", divisionLabel: "Copper", divisionRank: 63, gp: 8, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "小川芽依", jersey: 65, team: "日体大DREAMS Copper", divisionLabel: "Copper", divisionRank: 63, gp: 8, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "石井千咲", jersey: 91, team: "日体大DREAMS Copper", divisionLabel: "Copper", divisionRank: 63, gp: 8, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "田辺聖弥", jersey: 96, team: "ドラッカーズ", divisionLabel: "Copper", divisionRank: 63, gp: 8, goals: 0, assists: 1, points: 1, pim: 2 },
  { name: "川井淳那", jersey: 86, team: "日体大DREAMS Copper", divisionLabel: "Copper", divisionRank: 63, gp: 8, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "藤巻峻", jersey: 55, team: "風神雷神 Iron", divisionLabel: "Iron", divisionRank: 1, gp: 4, goals: 15, assists: 3, points: 18, pim: 0 },
  { name: "谷口駿", jersey: 5, team: "HCNK", divisionLabel: "Iron", divisionRank: 2, gp: 4, goals: 8, assists: 4, points: 12, pim: 0 },
  { name: "田川義延", jersey: 3, team: "風神雷神 Iron", divisionLabel: "Iron", divisionRank: 3, gp: 4, goals: 9, assists: 2, points: 11, pim: 0 },
  { name: "武居浩輝", jersey: 8, team: "風神雷神 Iron", divisionLabel: "Iron", divisionRank: 3, gp: 4, goals: 5, assists: 6, points: 11, pim: 0 },
  { name: "溝部千利", jersey: 8, team: "Flying Joke", divisionLabel: "Iron", divisionRank: 5, gp: 4, goals: 5, assists: 4, points: 9, pim: 0 },
  { name: "平松泰憲", jersey: 29, team: "サイコスクエア", divisionLabel: "Iron", divisionRank: 6, gp: 4, goals: 6, assists: 2, points: 8, pim: 0 },
  { name: "小田浩一郎", jersey: 14, team: "BigGate", divisionLabel: "Iron", divisionRank: 7, gp: 4, goals: 6, assists: 1, points: 7, pim: 0 },
  { name: "増田勝喜", jersey: 19, team: "Flying Joke", divisionLabel: "Iron", divisionRank: 7, gp: 4, goals: 5, assists: 2, points: 7, pim: 0 },
  { name: "小宮直樹", jersey: 56, team: "サイコスクエア", divisionLabel: "Iron", divisionRank: 9, gp: 4, goals: 4, assists: 2, points: 6, pim: 0 },
  { name: "内田亮宏", jersey: 10, team: "Over50's", divisionLabel: "Iron", divisionRank: 9, gp: 4, goals: 3, assists: 3, points: 6, pim: 0 },
  { name: "千葉諒", jersey: 19, team: "HCNK", divisionLabel: "Iron", divisionRank: 11, gp: 4, goals: 4, assists: 1, points: 5, pim: 0 },
  { name: "相沢邦彦", jersey: 48, team: "Over50's", divisionLabel: "Iron", divisionRank: 11, gp: 4, goals: 4, assists: 1, points: 5, pim: 0 },
  { name: "杉本圭一郎", jersey: 37, team: "ブルーフラグス", divisionLabel: "Iron", divisionRank: 11, gp: 4, goals: 2, assists: 3, points: 5, pim: 0 },
  { name: "渋谷弘美", jersey: 16, team: "風神雷神 Iron", divisionLabel: "Iron", divisionRank: 11, gp: 4, goals: 1, assists: 4, points: 5, pim: 2 },
  { name: "田代大作", jersey: 48, team: "サイコスクエア", divisionLabel: "Iron", divisionRank: 15, gp: 4, goals: 4, assists: 0, points: 4, pim: 0 },
  { name: "山本泰造", jersey: 6, team: "Flying Joke", divisionLabel: "Iron", divisionRank: 15, gp: 4, goals: 3, assists: 1, points: 4, pim: 0 },
  { name: "近藤勇人", jersey: 54, team: "HCNK", divisionLabel: "Iron", divisionRank: 15, gp: 4, goals: 3, assists: 1, points: 4, pim: 0 },
  { name: "乾正虎", jersey: 50, team: "Individuals Iron", divisionLabel: "Iron", divisionRank: 15, gp: 4, goals: 3, assists: 1, points: 4, pim: 0 },
  { name: "乾正樹", jersey: 7, team: "Individuals Iron", divisionLabel: "Iron", divisionRank: 15, gp: 4, goals: 2, assists: 2, points: 4, pim: 0 },
  { name: "梯公平", jersey: 41, team: "BigGate", divisionLabel: "Iron", divisionRank: 15, gp: 4, goals: 1, assists: 3, points: 4, pim: 0 },
  { name: "川野博之", jersey: 88, team: "Flying Joke", divisionLabel: "Iron", divisionRank: 15, gp: 4, goals: 1, assists: 3, points: 4, pim: 0 },
  { name: "瀧川拓也", jersey: 18, team: "HCNK", divisionLabel: "Iron", divisionRank: 22, gp: 4, goals: 3, assists: 0, points: 3, pim: 0 },
  { name: "牧野統", jersey: 96, team: "Over50's", divisionLabel: "Iron", divisionRank: 22, gp: 4, goals: 3, assists: 0, points: 3, pim: 0 },
  { name: "渡邊悦史", jersey: 21, team: "ブルーフラグス", divisionLabel: "Iron", divisionRank: 22, gp: 4, goals: 3, assists: 0, points: 3, pim: 0 },
  { name: "石井春道", jersey: 86, team: "Individuals Iron", divisionLabel: "Iron", divisionRank: 22, gp: 4, goals: 2, assists: 1, points: 3, pim: 0 },
  { name: "迫田秀夫", jersey: 59, team: "BigGate", divisionLabel: "Iron", divisionRank: 22, gp: 4, goals: 1, assists: 2, points: 3, pim: 0 },
  { name: "平塚, George", jersey: 13, team: "HCNK", divisionLabel: "Iron", divisionRank: 22, gp: 4, goals: 1, assists: 2, points: 3, pim: 2 },
  { name: "大廣恵三", jersey: 36, team: "BigGate", divisionLabel: "Iron", divisionRank: 28, gp: 4, goals: 2, assists: 0, points: 2, pim: 0 },
  { name: "佐久間日向", jersey: 55, team: "Individuals Iron", divisionLabel: "Iron", divisionRank: 28, gp: 4, goals: 2, assists: 0, points: 2, pim: 0 },
  { name: "堀尾卓史", jersey: 20, team: "Over50's", divisionLabel: "Iron", divisionRank: 28, gp: 4, goals: 2, assists: 0, points: 2, pim: 0 },
  { name: "齋藤由人", jersey: 87, team: "BigGate", divisionLabel: "Iron", divisionRank: 28, gp: 4, goals: 1, assists: 1, points: 2, pim: 0 },
  { name: "遠藤香澄", jersey: 55, team: "Flying Joke", divisionLabel: "Iron", divisionRank: 28, gp: 4, goals: 1, assists: 1, points: 2, pim: 0 },
  { name: "平野陽介", jersey: 7, team: "サイコスクエア", divisionLabel: "Iron", divisionRank: 28, gp: 4, goals: 1, assists: 1, points: 2, pim: 0 },
  { name: "高田泰男", jersey: 5, team: "ブルーフラグス", divisionLabel: "Iron", divisionRank: 28, gp: 4, goals: 1, assists: 1, points: 2, pim: 0 },
  { name: "田中登", jersey: 22, team: "Flying Joke", divisionLabel: "Iron", divisionRank: 35, gp: 4, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "鈴木凪", jersey: 16, team: "Individuals Iron", divisionLabel: "Iron", divisionRank: 35, gp: 4, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "Kim, Danu", jersey: 15, team: "Individuals Iron", divisionLabel: "Iron", divisionRank: 35, gp: 4, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "笹原裕基", jersey: 0, team: "サイコスクエア", divisionLabel: "Iron", divisionRank: 35, gp: 4, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "西原一紀", jersey: 36, team: "サイコスクエア", divisionLabel: "Iron", divisionRank: 35, gp: 4, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "宇田幸一", jersey: 11, team: "サイコスクエア", divisionLabel: "Iron", divisionRank: 35, gp: 4, goals: 1, assists: 0, points: 1, pim: 4 },
  { name: "末永浩", jersey: 86, team: "ブルーフラグス", divisionLabel: "Iron", divisionRank: 35, gp: 4, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "阿部駿哉", jersey: 11, team: "青学 Quzilax", divisionLabel: "Iron", divisionRank: 35, gp: 4, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "福田亘記", jersey: 50, team: "Individuals Iron", divisionLabel: "Iron", divisionRank: 35, gp: 4, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "五十嵐唯雄", jersey: 23, team: "Over50's", divisionLabel: "Iron", divisionRank: 35, gp: 4, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "松本航汰", jersey: 41, team: "青学 Quzilax", divisionLabel: "Iron", divisionRank: 35, gp: 4, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "水村康弘", jersey: 68, team: "風神雷神 Iron", divisionLabel: "Iron", divisionRank: 35, gp: 4, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "田原知典", jersey: 73, team: "風神雷神 Iron", divisionLabel: "Iron", divisionRank: 35, gp: 4, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "勅使川原小梅", jersey: 89, team: "日体大DREAMS WG", divisionLabel: "Women Gold", divisionRank: 1, gp: 3, goals: 9, assists: 7, points: 16, pim: 0 },
  { name: "奥津七海", jersey: 69, team: "Team SONIC", divisionLabel: "Women Gold", divisionRank: 2, gp: 3, goals: 7, assists: 3, points: 10, pim: 0 },
  { name: "小池望愛", jersey: 98, team: "日体大DREAMS WG", divisionLabel: "Women Gold", divisionRank: 3, gp: 3, goals: 7, assists: 2, points: 9, pim: 0 },
  { name: "森田真由", jersey: 95, team: "Team SONIC", divisionLabel: "Women Gold", divisionRank: 3, gp: 3, goals: 5, assists: 4, points: 9, pim: 0 },
  { name: "森香菜子", jersey: 39, team: "Team SONIC", divisionLabel: "Women Gold", divisionRank: 5, gp: 3, goals: 4, assists: 3, points: 7, pim: 2 },
  { name: "今野詩音", jersey: 64, team: "Team SONIC", divisionLabel: "Women Gold", divisionRank: 5, gp: 3, goals: 3, assists: 4, points: 7, pim: 0 },
  { name: "松岡侑依", jersey: 24, team: "Ginza Genkai Peanuts", divisionLabel: "Women Gold", divisionRank: 7, gp: 3, goals: 5, assists: 1, points: 6, pim: 2 },
  { name: "木原奈々子", jersey: 75, team: "Team SONIC", divisionLabel: "Women Gold", divisionRank: 7, gp: 3, goals: 4, assists: 2, points: 6, pim: 0 },
  { name: "大木寿梨", jersey: 17, team: "Ginza Genkai Peanuts", divisionLabel: "Women Gold", divisionRank: 9, gp: 3, goals: 1, assists: 4, points: 5, pim: 0 },
  { name: "是澤咲良", jersey: 56, team: "Ginza Genkai Peanuts", divisionLabel: "Women Gold", divisionRank: 10, gp: 3, goals: 3, assists: 0, points: 3, pim: 0 },
  { name: "伍井明日香", jersey: 22, team: "Ginza Genkai Peanuts", divisionLabel: "Women Gold", divisionRank: 10, gp: 3, goals: 0, assists: 3, points: 3, pim: 2 },
  { name: "小菅楓香", jersey: 27, team: "Ginza Genkai Peanuts", divisionLabel: "Women Gold", divisionRank: 12, gp: 3, goals: 2, assists: 0, points: 2, pim: 0 },
  { name: "早尾理沙", jersey: 37, team: "Team SONIC", divisionLabel: "Women Gold", divisionRank: 12, gp: 3, goals: 2, assists: 0, points: 2, pim: 2 },
  { name: "佐伯かりん", jersey: 14, team: "WeLLs", divisionLabel: "Women Gold", divisionRank: 12, gp: 3, goals: 2, assists: 0, points: 2, pim: 2 },
  { name: "西瑞姫", jersey: 21, team: "WeLLs", divisionLabel: "Women Gold", divisionRank: 12, gp: 3, goals: 2, assists: 0, points: 2, pim: 0 },
  { name: "樋野理恵", jersey: 37, team: "WeLLs", divisionLabel: "Women Gold", divisionRank: 12, gp: 3, goals: 2, assists: 0, points: 2, pim: 4 },
  { name: "堀口祐美", jersey: 17, team: "Ginza Genkai Peanuts", divisionLabel: "Women Gold", divisionRank: 12, gp: 3, goals: 1, assists: 1, points: 2, pim: 0 },
  { name: "加賀山愛", jersey: 88, team: "Team SONIC", divisionLabel: "Women Gold", divisionRank: 12, gp: 3, goals: 1, assists: 1, points: 2, pim: 0 },
  { name: "石井千咲", jersey: 1, team: "日体大DREAMS WG", divisionLabel: "Women Gold", divisionRank: 12, gp: 3, goals: 1, assists: 1, points: 2, pim: 0 },
  { name: "岩崎玲", jersey: 63, team: "Ginza Genkai Peanuts", divisionLabel: "Women Gold", divisionRank: 20, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "義澤遥花", jersey: 24, team: "Team SONIC", divisionLabel: "Women Gold", divisionRank: 20, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "鴻嶋萌々香", jersey: 19, team: "WeLLs", divisionLabel: "Women Gold", divisionRank: 20, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "高根碧", jersey: 9, team: "WeLLs", divisionLabel: "Women Gold", divisionRank: 20, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "大橋莉子", jersey: 93, team: "日体大DREAMS WG", divisionLabel: "Women Gold", divisionRank: 20, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "井田樹", jersey: 12, team: "Ginza Genkai Peanuts", divisionLabel: "Women Gold", divisionRank: 20, gp: 3, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "伊藤陽", jersey: 77, team: "Ginza Genkai Peanuts", divisionLabel: "Women Gold", divisionRank: 20, gp: 3, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "山本万葉", jersey: 84, team: "WeLLs", divisionLabel: "Women Gold", divisionRank: 20, gp: 3, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "髙山智宏", jersey: 4, team: "Flying Penguins 35", divisionLabel: "35&Over", divisionRank: 1, gp: 4, goals: 10, assists: 20, points: 30, pim: 0 },
  { name: "林寛和", jersey: 99, team: "武田園", divisionLabel: "35&Over", divisionRank: 2, gp: 4, goals: 9, assists: 5, points: 14, pim: 0 },
  { name: "田川靖丈", jersey: 18, team: "武田園", divisionLabel: "35&Over", divisionRank: 3, gp: 4, goals: 9, assists: 3, points: 12, pim: 0 },
  { name: "浅沼昌平", jersey: 21, team: "武田園", divisionLabel: "35&Over", divisionRank: 4, gp: 4, goals: 7, assists: 4, points: 11, pim: 0 },
  { name: "塩原将志", jersey: 33, team: "Flying Penguins 35", divisionLabel: "35&Over", divisionRank: 5, gp: 4, goals: 8, assists: 1, points: 9, pim: 0 },
  { name: "高崎寛之", jersey: 12, team: "武田園", divisionLabel: "35&Over", divisionRank: 5, gp: 4, goals: 8, assists: 1, points: 9, pim: 0 },
  { name: "榎本盛介", jersey: 98, team: "武田園", divisionLabel: "35&Over", divisionRank: 5, gp: 4, goals: 3, assists: 6, points: 9, pim: 0 },
  { name: "Tyler, Pernell", jersey: 58, team: "STIGA 35", divisionLabel: "35&Over", divisionRank: 8, gp: 4, goals: 7, assists: 0, points: 7, pim: 4 },
  { name: "小宮直樹", jersey: 2, team: "Individuals 35", divisionLabel: "35&Over", divisionRank: 8, gp: 3, goals: 6, assists: 1, points: 7, pim: 0 },
  { name: "白谷友和", jersey: 95, team: "Flying Penguins 35", divisionLabel: "35&Over", divisionRank: 8, gp: 4, goals: 4, assists: 3, points: 7, pim: 0 },
  { name: "伊原克将", jersey: 49, team: "STIGA 35", divisionLabel: "35&Over", divisionRank: 8, gp: 4, goals: 4, assists: 3, points: 7, pim: 0 },
  { name: "井手隆弘", jersey: 14, team: "Individuals 35", divisionLabel: "35&Over", divisionRank: 12, gp: 3, goals: 1, assists: 5, points: 6, pim: 0 },
  { name: "原田猛", jersey: 83, team: "Flying Penguins 35", divisionLabel: "35&Over", divisionRank: 13, gp: 4, goals: 4, assists: 1, points: 5, pim: 2 },
  { name: "勝野貴志", jersey: 75, team: "STIGA 35", divisionLabel: "35&Over", divisionRank: 13, gp: 4, goals: 3, assists: 2, points: 5, pim: 0 },
  { name: "伍井明日香", jersey: 15, team: "武田園", divisionLabel: "35&Over", divisionRank: 13, gp: 4, goals: 1, assists: 4, points: 5, pim: 0 },
  { name: "坂田哲也", jersey: 23, team: "Flying Penguins 35", divisionLabel: "35&Over", divisionRank: 16, gp: 4, goals: 4, assists: 0, points: 4, pim: 0 },
  { name: "若林孝一", jersey: 51, team: "Flying Penguins 35", divisionLabel: "35&Over", divisionRank: 16, gp: 4, goals: 4, assists: 0, points: 4, pim: 0 },
  { name: "下平晃", jersey: 18, team: "STIGA 35", divisionLabel: "35&Over", divisionRank: 18, gp: 4, goals: 2, assists: 1, points: 3, pim: 0 },
  { name: "鈴木智満", jersey: 1, team: "武田園", divisionLabel: "35&Over", divisionRank: 18, gp: 4, goals: 0, assists: 3, points: 3, pim: 0 },
  { name: "八藤信幸", jersey: 8, team: "Individuals 35", divisionLabel: "35&Over", divisionRank: 20, gp: 3, goals: 2, assists: 0, points: 2, pim: 0 },
  { name: "浪本雅和", jersey: 79, team: "たたかえ！！ホイジンガー", divisionLabel: "35&Over", divisionRank: 20, gp: 3, goals: 2, assists: 0, points: 2, pim: 0 },
  { name: "宮崎正弘", jersey: 94, team: "Flying Penguins 35", divisionLabel: "35&Over", divisionRank: 20, gp: 4, goals: 1, assists: 1, points: 2, pim: 2 },
  { name: "宮城努", jersey: 10, team: "STIGA 35", divisionLabel: "35&Over", divisionRank: 20, gp: 4, goals: 1, assists: 1, points: 2, pim: 0 },
  { name: "古屋博隆", jersey: 16, team: "武田園", divisionLabel: "35&Over", divisionRank: 20, gp: 4, goals: 0, assists: 2, points: 2, pim: 0 },
  { name: "増田満久", jersey: 32, team: "Flying Penguins 35", divisionLabel: "35&Over", divisionRank: 25, gp: 4, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "飯塚宜行", jersey: 30, team: "Individuals 35", divisionLabel: "35&Over", divisionRank: 25, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "角丸貴洋", jersey: 62, team: "STIGA 35", divisionLabel: "35&Over", divisionRank: 25, gp: 4, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "野崎誠", jersey: 9, team: "たたかえ！！ホイジンガー", divisionLabel: "35&Over", divisionRank: 25, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "田中康寛", jersey: 28, team: "たたかえ！！ホイジンガー", divisionLabel: "35&Over", divisionRank: 25, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "藤田欣宏", jersey: 74, team: "たたかえ！！ホイジンガー", divisionLabel: "35&Over", divisionRank: 25, gp: 3, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "松岡徹", jersey: 99, team: "武田園", divisionLabel: "35&Over", divisionRank: 25, gp: 4, goals: 1, assists: 0, points: 1, pim: 0 },
  { name: "須永冝司", jersey: 2, team: "STIGA 35", divisionLabel: "35&Over", divisionRank: 25, gp: 4, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "三浦建太郎", jersey: 44, team: "たたかえ！！ホイジンガー", divisionLabel: "35&Over", divisionRank: 25, gp: 3, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "奥野加奈", jersey: 21, team: "たたかえ！！ホイジンガー", divisionLabel: "35&Over", divisionRank: 25, gp: 3, goals: 0, assists: 1, points: 1, pim: 1 },
  { name: "染谷克典", jersey: 8, team: "たたかえ！！ホイジンガー", divisionLabel: "35&Over", divisionRank: 25, gp: 3, goals: 0, assists: 1, points: 1, pim: 0 },
  { name: "竹村昭紀", jersey: 14, team: "たたかえ！！ホイジンガー", divisionLabel: "35&Over", divisionRank: 25, gp: 3, goals: 0, assists: 1, points: 1, pim: 0 },
];

export async function GET(): Promise<NextResponse> {
  try {
    const cached = await kv.get<PrevPlayerStat[]>(KV_KEY);
    if (cached && cached.length > 0) {
      return NextResponse.json({ season: 52, players: cached });
    }
  } catch {}

  try {
    await kv.set(KV_KEY, SEASON_52_PLAYERS);
  } catch {}

  return NextResponse.json({ season: 52, players: SEASON_52_PLAYERS });
}
